### ISSUE TITLE
DeprecationWarning for OutgoingMessage.prototype._headers

### ISSUE THREAD

**Issue by rgladwell** [indexzero/http-server#537]
Accessing the HTTP server throws a DeprecationWarning for OutgoingMessage.prototype._headers on Node version 12.3.1.

```javascript
const puppeteer = require('puppeteer')
const httpServer = require('http-server')
const server = httpServer.createServer({ root: 'dist/html/' })
server.listen(8080)

const browser = await puppeteer.launch({
  headless: true,
  args: ['--no-sandbox', '--disable-setuid-sandbox']
})

const page = await browser.newPage()
await page.goto('http://localhost:8080', { waitUntil: 'networkidle0' })
```

**What did you expect to happen?**

No deprecation warning.

**What actually happened?**

Got the following warning:

```
(node:59243) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **http-server version:** 0.11.1
- **Platform:** Mac (Node 10.14.5 12.3.1)

**Comment by Xmader** [comment]
https://github.com/flatiron/union/pull/64

**Comment by Smilebags** [comment]
The same occurs when using `http-server` from the command line. I wonder if this could be resolved?

**Comment by Lemraj** [comment]
I am having the same problem when running http-server (local).

I have a simple angular app:
1 - **ng build --prod**
2 - go to **dist/{name-app}**
3 - run **http-server**

when browsing the url i get the following error:

![image](https://user-images.githubusercontent.com/10677560/67230766-353f4780-f43e-11e9-9a2d-15dfaec38f0b.png)

![image](https://user-images.githubusercontent.com/10677560/67230871-6ddf2100-f43e-11e9-8895-92f22a9b4f95.png)

**Comment by thornjad** [comment]
This is an issue in `union` (flatiron/union#64) which we're planning to remove from http-server down the road (#483). I'm not going to close this issue though, to ensure we make sure it goes away after #483 is resolved.

**Comment by gnganpath** [comment]
node -v 10.x is solved. thanks

**Comment by rsail** [comment]
Is there an ETA when this will be resolved?

**Comment by stoufa** [comment]
Continuing @rsail 's comment: ... and what can we do in the meanwhile (as a quick hotfix)?

**Comment by jmcollin78** [comment]
Always the problem with very latest build (April 2021). An estimated ETA or fix would be greatly appreciated

**Comment by Dragonrun1** [comment]
Over 2 years now. How much longer until this is fixed?

**Comment by Saqib92** [comment]
I was running another server on same port (using XAMPP server). I stopped XAMPP and restarted my cmd and its working now.

**Comment by rich1n** [comment]
Still the bug alive? or it is solved?

**Comment by thornjad** [comment]
This is an upstream bug in the dependency `union`, which is more or less unmaintained. #483 seeks to remove it, but it will take some substantial work. For the time being, I'm not aware of plans to imminently remove the `_headers` property in Node, so we're not at a crisis point yet. I may not have the time to get to #483 for a while, and would welcome any PRs.

**Comment by spacecowgoesmoo** [comment]
Still happening

**Comment by ssaakkiii** [comment]
Can't believe it's now 2022 and the problem still exists... Orz

**Comment by ssaakkiii** [comment]
Can't believe it's now 2022 and the bug still exists... Orz

**Comment by Eli250** [comment]
I have met the same error

**Comment by pingan8787** [comment]
+2

**Comment by shinelp100** [comment]
+3

**Comment by Zwiqler94** [comment]
Any updates on this?

**Comment by mirabilos** [comment]
Might be useful to spin a new version of union fixing just this…?

**Comment by pingan8787** [comment]
平安已经收到你的邮件啦

**Comment by Jaystar-Bee** [comment]
This issue is still not fixed yet!!

**Comment by JobinZe** [comment]
Is there any solution for this?

**Comment by kburns2kb** [comment]
Howdy, still not fixed

**Comment by MarwenLabidi** [comment]
same problem

**Comment by omarzougui** [comment]
Same problem on Nx monorepo with node v19.7.0

**Comment by jaanus** [comment]
Another passer-by surprised by this bug. Was looking for a small Node static web server to run a static site so I can Playwright tests against it during development/CI. This project seems to fit the bill, but this warning is unfortunate.

**Comment by akadori** [comment]
same problem.

**Comment by work933k** [comment]
Same here

**Comment by lolhie3** [comment]
Same with node v18.15.0 :(
![Screenshot_9081788a87c](https://github.com/http-party/http-server/assets/96627041/9ed3bc8f-6b45-437f-8448-e0367d293130)

**Comment by FunctionPoint** [comment]
Please fix..

**Comment by vitalets** [comment]
Temporary solution is to suppress Node.js warnings:
```
NODE_NO_WARNINGS=1 npx http-server .
```

**Comment by muhamedoufi** [comment]
try ``npm audit fix --force ``

**Comment by elmalving** [comment]
As the status says - the issue is still open ;-;
